---
version: '3.7'

services:

  dhcp:
    image: ghcr.io/opiproject/opi-dhcp-server:main
    environment:
      NODE_IP_SUBNET: 10.127.127.0
      NODE_IP_NETMASK: 255.255.255.0
      NODE_IP_RANGE_MIN: 10.127.127.100
      NODE_IP_RANGE_MAX: 10.127.127.253
      NODE_IP_ADDRESS: 10.127.127.3
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.3
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: sh -e -u -x -c 'envsubst < /etc/dhcp/dhcpd.conf.template > /etc/dhcp/dhcpd.conf && dhcpd -d'

  nmap:
    image: docker.io/instrumentisto/nmap:7.93
    networks:
      - xpu-cpu
    command: --script broadcast-dhcp-discover

  web:
    image: docker.io/library/python:3.11.0-slim
    ports:
      - 8082:8082
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.16
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: python3 -m http.server 8082

  sztp:
    image: ghcr.io/opiproject/opi-sztp-server:main
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.11
    command: ['sztpd', 'sqlite:///:memory:']
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]

networks:
  xpu-cpu:
    external: true
