version: "3.7"

services:

  otel-gw-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:z
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      high-speed-external:
        ipv4_address: 10.129.129.6
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8086/ping || exit 1
      interval: 6s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml:z
    ports:
      - "9091:9090"
    networks:
      high-speed-external:
        ipv4_address: 10.129.129.5

networks:
  high-speed-external:
    external: true
