---
version: '3.7'

services:

  xpu-cpu-ssh:
    image: linuxserver/openssh-server:8.8_p1-r1-ls84
    hostname: xpu-cpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=xpu
    ports:
      - '2207:2222'  # ssh
      - "9009:9009"  # spdk
      - "127.0.0.1:8011:8001/tcp"
      - "127.0.0.1:8444:8444/tcp"
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.7
      high-speed-external:
        ipv4_address: 10.129.129.7
      xpu-ncsi:
        ipv4_address: 10.131.131.7
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-cpu:
    build:
      context: xpu-cpu
    depends_on:
      - xpu-cpu-ssh
    volumes_from:
      - xpu-cpu-ssh:rw
    network_mode: service:xpu-cpu-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']
    healthcheck:
      test: cat /proc/1/status || exit 1
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-telegraf:
    build:
      context: xpu-cpu
      dockerfile: Dockerfile.telegraf
    depends_on:
      - xpu-spdk-web
    network_mode: service:xpu-cpu-ssh
    privileged: true

  xpu-spdk:
    image: ghcr.io/opiproject/opi-storage-spdk:main@sha256:55db45836bb24898798799211d803a23b120f52c8aba87fa0392fa85605bd65d
    volumes:
      - /dev/hugepages:/dev/hugepages
      - /dev/shm:/dev/shm
      - /proc:/proc
      - /var/tmp:/var/tmp
    privileged: true
    network_mode: service:xpu-cpu-ssh
    working_dir: /usr/libexec/spdk/scripts
    command: |
      sh -x -c 'sync; echo 1 > /proc/sys/vm/drop_caches  && \
            mkdir -p /mnt/huge && \
            grep hugetlbfs /proc/mounts || mount -t hugetlbfs nodev /mnt/huge && \
            echo 1024 > /proc/sys/vm/nr_hugepages && \
            grep "" /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages && \
            /usr/local/bin/spdk_tgt -m 0x1 -s 512 --no-pci 2>&1 & \
            for i in `seq 1 10`; do ./rpc.py spdk_get_version && break || sleep 1; done  && \
            ./rpc.py bdev_malloc_create -b Malloc0 64 512 && \
            ./rpc.py bdev_malloc_create -b Malloc1 64 512 && \
            echo ./rpc.py bdev_nvme_attach_controller -b opi-bdev -t tcp -a spdk-target -f ipv4 -s 4420 -n nqn.2016-06.io.spdk:cnode1 && \
            wait'
    healthcheck:
      test: ["CMD-SHELL", "python3 /usr/libexec/spdk/scripts/rpc.py spdk_get_version || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-spdk-web:
    image: ghcr.io/opiproject/opi-storage-spdk:main@sha256:55db45836bb24898798799211d803a23b120f52c8aba87fa0392fa85605bd65d
    volumes_from:
      - xpu-spdk:rw
    network_mode: service:xpu-cpu-ssh
    working_dir: /usr/libexec/spdk/scripts
    command: |
        sh -x -c 'sync && \
            for i in `seq 1 10`; do ./rpc.py spdk_get_version && break || sleep 1; done  && \
            ./rpc_http_proxy.py 0.0.0.0 9009 spdkuser spdkpass'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  strongswan:
    image: strongx509/strongswan:5.9.9
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./strongswan/server:/etc/swanctl:z
      - ./strongswan/strongswan.conf:/etc/strongswan.conf:z
    network_mode: service:xpu-cpu-ssh
    command: './charon'
    healthcheck:
      test: swanctl --stats || exit 1

  xpu-bmc-ssh:
    image: linuxserver/openssh-server:8.8_p1-r1-ls84
    hostname: xpu-bmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=bmc
    ports:
      - '2209:2222'  # ssh
      - '8002:8000'  # redfish
    networks:
      bmc:
        ipv4_address: 10.128.128.9
      xpu-ncsi:
        ipv4_address: 10.131.131.9
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  xpu-bmc-redfish:
    image: dmtf/redfish-mockup-server:1.2.1
    network_mode: service:xpu-bmc-ssh

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - example-network
      - example-storage
    ports:
      - "50051:50051"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=50051
    healthcheck:
      test: curl --fail http://localhost:50051/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    networks:
      gateway:

  example-network:
    build:
      context: gateway
      dockerfile: Dockerfile.network
    networks:
      gateway:
  example-storage:
    build:
      context: gateway
      dockerfile: Dockerfile.storage
    networks:
      gateway:
  example-network-client:
    depends_on:
      - gateway
      - example-network
      - example-storage
    build:
      context: gateway
      dockerfile: Dockerfile.network
    network_mode: host
    command: |
        sh -x -c 'for i in `seq 1 5`; \
            do \
                sleep 1; \
                python route_guide_client.py && break; \
            done'
  example-storage-client:
    depends_on:
      - gateway
      - example-network
      - example-storage
    build:
      context: gateway
      dockerfile: Dockerfile.storage
    network_mode: host
    command: |
        sh -x -c 'for i in `seq 1 5`; \
            do \
                sleep 1; \
                go run ./greeter_client/main.go && break; \
            done'

networks:
  xpu-cpu:
    external: true
  bmc:
    external: true
  high-speed-external:
    external: true
  gateway:
    external: true
