---
version: '3.7'

services:

  dhcp:
    image: ghcr.io/opiproject/opi-dhcp-server:main@sha256:c2dbd09e21004ded6707ff713c43f296eab00d4e94a72be20358364588f06e4a
    environment:
      NODE_IP_SUBNET: 10.127.127.0
      NODE_IP_NETMASK: 255.255.255.0
      NODE_IP_RANGE_MIN: 10.127.127.100
      NODE_IP_RANGE_MAX: 10.127.127.253
      NODE_IP_ADDRESS: 10.127.127.3
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.3
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: sh -e -u -x -c 'envsubst < /etc/dhcp/dhcpd.conf.template > /etc/dhcp/dhcpd.conf && dhcpd -d'

  nmap:
    image: docker.io/instrumentisto/nmap:7.93
    networks:
      - xpu-cpu
    command: --script broadcast-dhcp-discover

  web:
    image: ghcr.io/opiproject/opi-web:main@sha256:758c0bb782be49c18832d5d6aa0fb45f5703ced8e0258464f22921bc277a7711
    ports:
      - 8082:8082
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.16
    healthcheck:
      test: curl --silent --fail http://localhost:8082 || exit 1
    command: python3 -m http.server 8082

  bootstrap:
    image: ghcr.io/opiproject/opi-sztp-server:main@sha256:b93b5ca3ad3a8b35ea01fdcdd27bf30f2e3a4a6666454f7df9c8d12fd49e3e73
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_SBI_PORT: 9090
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
      SZTPD_OPI_MODE: "running"
    entrypoint: bash
    command: -c "sed -i 's/1 10/1 30/g' /usr/local/bin/docker-entrypoint.sh && /usr/local/bin/docker-entrypoint.sh"
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.11
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]

  redirecter:
    image: ghcr.io/opiproject/opi-sztp-server:main@sha256:b93b5ca3ad3a8b35ea01fdcdd27bf30f2e3a4a6666454f7df9c8d12fd49e3e73
    environment:
      SZTPD_INIT_PORT: 1080
      SZTPD_SBI_PORT: 8080
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
      BOOTSVR_PORT: 9090
      BOOTSVR_ADDR: "bootstrap"
      SZTPD_OPI_MODE: "redirect"
    entrypoint: bash
    command: -c "sed -i 's/1 10/1 30/g' /usr/local/bin/docker-entrypoint.sh && /usr/local/bin/docker-entrypoint.sh"
    networks:
      xpu-cpu:
        ipv4_address: 10.127.127.12
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]

  dhclient:
    image: ghcr.io/opiproject/opi-dhcp-client:main@sha256:28f99c710308edb6262bb7d426f415387e860bee2615e8934bc9990308c34bae
    cap_add:
      - CAP_NET_RAW
    volumes:
      - dhcp-leases-folder:/var/lib/dhclient/
    network_mode: service:web
    command: dhclient -d -v

  agent:
    image: ghcr.io/opiproject/opi-sztp-agent:main@sha256:ec0727cd122dc80e0286767655de76a32597d3ec6772acbf1a21abb32db5e6fc
    depends_on:
      bootstrap:
        condition: service_healthy
      redirecter:
        condition: service_healthy
    volumes_from:
      - dhclient:ro
    networks:
      - xpu-cpu
    command: ['/opi-sztp-agent', 'daemon']

volumes:
  dhcp-leases-folder:

networks:
  xpu-cpu:
    external: true
