---
version: "3.7"

services:

  spdk-target:
    image: ghcr.io/opiproject/spdk:main@sha256:7819eea617fe72a403df7772fdf418ce123e85c1556fdee7bc3a3f639e2afa8a
    volumes:
      - /dev/hugepages:/dev/hugepages
      - /dev/shm:/dev/shm
      - /proc:/proc
      - /var/tmp/
    privileged: true
    networks:
      high-speed-external:
        ipv4_address: 10.129.129.4
    working_dir: /usr/libexec/spdk/scripts
    command: |
      sh -x -c 'sync; echo 1 > /proc/sys/vm/drop_caches  && \
            mkdir -p /mnt/huge && \
            grep hugetlbfs /proc/mounts || mount -t hugetlbfs nodev /mnt/huge && \
            echo 1024 > /proc/sys/vm/nr_hugepages && \
            grep "" /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages && \
            /usr/local/bin/spdk_tgt -m 0x1 -s 512 --no-pci 2>&1 & \
            for i in `seq 1 10`; do ./rpc.py spdk_get_version && break || sleep 1; done  && \
            ./rpc.py bdev_malloc_create -b Malloc0 64 512 && \
            ./rpc.py bdev_malloc_create -b Malloc1 64 512 && \
            ./rpc.py nvmf_create_transport -t TCP -u 8192 -m 4 -c 0  && \
            ./rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1  && \
            ./rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.129.129.4 -s 4420  && \
            ./rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0 -n 1  && \
            ./rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1 -n 2  && \
            wait'
    healthcheck:
      test: ["CMD-SHELL", "python3 /usr/libexec/spdk/scripts/rpc.py spdk_get_version || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  spdk-target-web:
    image: ghcr.io/opiproject/spdk:main@sha256:7819eea617fe72a403df7772fdf418ce123e85c1556fdee7bc3a3f639e2afa8a
    volumes_from:
      - spdk-target:rw
    ports:
      - "9004:9009"
    networks:
      high-speed-external:
        ipv4_address: 10.129.129.8
    working_dir: /usr/libexec/spdk/scripts
    command: |
        sh -x -c 'sync && \
            for i in `seq 1 10`; do ./rpc.py spdk_get_version && break || sleep 1; done  && \
            ./rpc_http_proxy.py 0.0.0.0 9009 spdkuser spdkpass'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure --user spdkuser:spdkpass -X POST -H 'Content-Type: application/json' -d '{\"id\": 1, \"method\": \"bdev_get_bdevs\"}' http://localhost:9009 || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  high-speed-external:
    external: true
