version: '3.7'

services:

  host-cpu-ssh:
    image: linuxserver/openssh-server:8.8_p1-r1-ls84
    hostname: host-cpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=host
    ports:
      - '2210:2222'
    networks:
      high-speed-external:
        ipv4_address: 10.129.129.10
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  host-cpu:
    build:
      context: host-cpu
    depends_on:
      - host-cpu-ssh
    volumes_from:
      - host-cpu-ssh:rw
    network_mode: service:host-cpu-ssh
    command: ['/bin/sh', '-c', 'sleep infinity']
    healthcheck:
      test: cat /proc/1/status || exit 1
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  host-telegraf:
    build:
      context: host-cpu
      dockerfile: Dockerfile.telegraf
    network_mode: service:host-cpu-ssh
    privileged: true

  host-bmc-ssh:
    image: linuxserver/openssh-server:8.8_p1-r1-ls84
    hostname: host-bmc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=123456
      - USER_NAME=bmc
    ports:
      - '2208:2222'
      - '8001:8000'
    networks:
      bmc:
        ipv4_address: 10.128.128.8
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/2222'"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  host-bmc-redfish:
    image: dmtf/redfish-mockup-server:1.1.8
    network_mode: service:host-bmc-ssh

networks:
  high-speed-external:
    external: true
  bmc:
    external: true
