---
name: 'OPI Networking PoC CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'networking/**'
      - '.github/workflows/poc-networking.yml'
      - '.github/workflows/poc-networking-poc.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'networking/**'
      - '.github/workflows/poc-networking.yml'
      - '.github/workflows/poc-networking-poc.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: makefile-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: networking shellcheck
      run: |
        make -C networking shellcheck

  run_networking_poc:
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup IPDK
      run: |
        docker pull ghcr.io/ipdk-io/ipdk-ebpf-ubuntu2004-x86_64:main
        git clone https://github.com/ipdk-io/ipdk.git
        pushd ipdk/build
        ./ipdk install ebpf-ubuntu2004
        echo "TAG=main" >> ~/.ipdk/ipdk.env
        popd || exit

    - name: Install ipdk-plugin
      run: |
        mkdir -p ~/go/src
        pushd ~/go/src || exit
        git clone https://github.com/mestery/ipdk-plugin.git
        cd ipdk-plugin
        go get
        go build
        sudo mkdir -p /etc/docker/plugins
        sudo cp ipdk.json /etc/docker/plugins
        popd || exit

    - name: Run Networking PoC
      run: |
        cd networking && ./scripts/poc.sh start
